export const GET_ALL_COUPONS_START = "GET_ALL_COUPONS_START";
export const GET_ALL_COUPONS_SUCCESS = "GET_ALL_COUPONS_SUCCESS";
export const GET_ALL_COUPONS_ERROR = "GET_ALL_COUPONS_ERROR";

export const GET_COUPON_START = "GET_COUPON_START";
export const GET_COUPON_SUCCESS = "GET_COUPON_SUCCESS";
export const GET_COUPON_ERROR = "GET_COUPON_ERROR";

export const CREATE_COUPON_START = "CREATE_COUPON_START";
export const CREATE_COUPON_SUCCESS = "CREATE_COUPON_SUCCESS";
export const CREATE_COUPON_ERROR = "CREATE_COUPON_ERROR";

export const UPDATE_COUPON_START = "UPDATE_COUPON_START";
export const UPDATE_COUPON_SUCCESS = "UPDATE_COUPON_SUCCESS";
export const UPDATE_COUPON_ERROR = "UPDATE_COUPON_ERROR";

export const UPDATE_COUPON_STATUS_START = "UPDATE_COUPON_STATUS_START";
export const UPDATE_COUPON_STATUS_SUCCESS = "UPDATE_COUPON_STATUS_SUCCESS";
export const UPDATE_COUPON_STATUS_ERROR = "UPDATE_COUPON_STATUS_ERROR";

export const DELETE_COUPON_START = "DELETE_COUPON_START";
export const DELETE_COUPON_SUCCESS = "DELETE_COUPON_SUCCESS";
export const DELETE_COUPON_ERROR = "DELETE_COUPON_ERROR";

export const RESET_COUPON = "RESET_COUPON";