export const CREATE_SCHEDULE_AVAILABILITY_START =
  "CREATE_SCHEDULE_AVAILABILITY_START";
export const CREATE_SCHEDULE_AVAILABILITY_SUCCESS =
  "CREATE_SCHEDULE_AVAILABILITY_SUCCESS";
export const CREATE_SCHEDULE_AVAILABILITY_ERROR =
  "CREATE_SCHEDULE_AVAILABILITY_ERROR";

export const FETCH_AVAILABILITY_BY_USER_ID_START =
  "FETCH_AVAILABILITY_BY_USER_ID_START";
export const FETCH_AVAILABILITY_BY_USER_ID_SUCCESS =
  "FETCH_AVAILABILITY_BY_USER_ID_SUCCESS";
export const FETCH_AVAILABILITY_BY_USER_ID_ERROR =
  "FETCH_AVAILABILITY_BY_USER_ID_ERROR";

export const CREATE_APPOINTMENT_SCHEDULE_START =
  "CREATE_APPOINTMENT_SCHEDULE_START";
export const CREATE_APPOINTMENT_SCHEDULE_SUCCESS =
  "CREATE_APPOINTMENT_SCHEDULE_SUCCESS";
export const CREATE_APPOINTMENT_SCHEDULE_ERROR =
  "CREATE_APPOINTMENT_SCHEDULE_ERROR";

export const UPDATE_SCHEDULE_AVAILABILITY_START = "UPDATE_SCHEDULE_AVAILABILITY_START";
export const UPDATE_SCHEDULE_AVAILABILITY_SUCCESS = "UPDATE_SCHEDULE_AVAILABILITY_SUCCESS";
export const UPDATE_SCHEDULE_AVAILABILITY_ERROR = "UPDATE_SCHEDULE_AVAILABILITY_ERROR";

export const FETCH_PICKUP_LOCATION_TYPES_START =
  "FETCH_PICKUP_LOCATION_TYPES_START";
export const FETCH_PICKUP_LOCATION_TYPES_SUCCESS =
  "FETCH_PICKUP_LOCATION_TYPES_SUCCESS";
export const FETCH_PICKUP_LOCATION_TYPES_ERROR =
  "FETCH_PICKUP_LOCATION_TYPES_ERROR";

export const FETCH_AVAILABILITY_WITH_PARAMS_START =
  "FETCH_AVAILABILITY_WITH_PARAMS_START";
export const FETCH_AVAILABILITY_WITH_PARAMS_SUCCESS =
  "FETCH_AVAILABILITY_WITH_PARAMS_SUCCESS";
export const FETCH_AVAILABILITY_WITH_PARAMS_ERROR =
  "FETCH_AVAILABILITY_WITH_PARAMS_ERROR";

export const FETCH_SCHEDULE_APPOINTMENT_LIST_START =
  "FETCH_SCHEDULE_APPOINTMENT_LIST_START";
export const FETCH_SCHEDULE_APPOINTMENT_LIST_SUCCESS =
  "FETCH_SCHEDULE_APPOINTMENT_LIST_SUCCESS";
export const FETCH_SCHEDULE_APPOINTMENT_LIST_ERROR =
  "FETCH_SCHEDULE_APPOINTMENT_LIST_ERROR";

export const FETCH_INSTRUCTOR_MONTHLY_AVAILABILITY_START =
  "FETCH_INSTRUCTOR_MONTHLY_AVAILABILITY_START";
export const FETCH_INSTRUCTOR_MONTHLY_AVAILABILITY_SUCCESS =
  "FETCH_INSTRUCTOR_MONTHLY_AVAILABILITY_SUCCESS";
export const FETCH_INSTRUCTOR_MONTHLY_AVAILABILITY_ERROR =
  "FETCH_INSTRUCTOR_MONTHLY_AVAILABILITY_ERROR";

export const FETCH_AVAILABILITY_MONTHLY_START =
  "FETCH_AVAILABILITY_MONTHLY_START";
export const FETCH_AVAILABILITY_MONTHLY_SUCCESS =
  "FETCH_AVAILABILITY_MONTHLY_SUCCESS";
export const FETCH_AVAILABILITY_MONTHLY_ERROR =
  "FETCH_AVAILABILITY_MONTHLY_ERROR";

export const FETCH_AVAILABILITY_WEEKLY_START =
  "FETCH_AVAILABILITY_WEEKLY_START";
export const FETCH_AVAILABILITY_WEEKLY_SUCCESS =
  "FETCH_AVAILABILITY_WEEKLY_SUCCESS";
export const FETCH_AVAILABILITY_WEEKLY_ERROR =
  "FETCH_AVAILABILITY_WEEKLY_ERROR";

export const FETCH_DATE_SPECIFIC_AVAILABILITY_START =
  "FETCH_DATE_SPECIFIC_AVAILABILITY_START";
export const FETCH_DATE_SPECIFIC_AVAILABILITY_SUCCESS =
  "FETCH_DATE_SPECIFIC_AVAILABILITY_SUCCESS";
export const FETCH_DATE_SPECIFIC_AVAILABILITY_ERROR =
  "FETCH_DATE_SPECIFIC_AVAILABILITY_ERROR";

export const DELETE_AVAILABILITY_START = "DELETE_AVAILABILITY_START";
export const DELETE_AVAILABILITY_SUCCESS = "DELETE_AVAILABILITY_SUCCESS";
export const DELETE_AVAILABILITY_ERROR = "DELETE_AVAILABILITY_ERROR";

export const FETCH_INSTRUCTOR_MONTHLY_SCHEDULE_START =
  "FETCH_INSTRUCTOR_MONTHLY_SCHEDULE_START";
export const FETCH_INSTRUCTOR_MONTHLY_SCHEDULE_SUCCESS =
  "FETCH_INSTRUCTOR_MONTHLY_SCHEDULE_SUCCESS";
export const FETCH_INSTRUCTOR_MONTHLY_SCHEDULE_ERROR =
  "FETCH_INSTRUCTOR_MONTHLY_SCHEDULE_ERROR";

export const UPDATE_APPOINTMENT_SCHEDULE_START = "UPDATE_APPOINTMENT_SCHEDULE_START";
export const UPDATE_APPOINTMENT_SCHEDULE_SUCCESS = "UPDATE_APPOINTMENT_SCHEDULE_SUCCESS";
export const UPDATE_APPOINTMENT_SCHEDULE_ERROR = "UPDATE_APPOINTMENT_SCHEDULE_ERROR";

export const FETCH_APPOINTMENT_BY_APPOINTMENT_ID_START = "FETCH_APPOINTMENT_BY_APPOINTMENT_ID_START";
export const FETCH_APPOINTMENT_BY_APPOINTMENT_ID_SUCCESS = "FETCH_APPOINTMENT_BY_APPOINTMENT_ID_SUCCESS";
export const FETCH_APPOINTMENT_BY_APPOINTMENT_ID_ERROR = "FETCH_APPOINTMENT_BY_APPOINTMENT_ID_ERROR";


export const RESET_INSTRUCTOR_MONTHLY_AVAILABILITY = "RESET_INSTRUCTOR_MONTHLY_AVAILABILITY";
export const RESET_APPOINTMENT_BY_ID = "RESET_APPOINTMENT_BY_ID";

export const CREATE_DAY_OFF_START = "CREATE_DAY_OFF_START";
export const CREATE_DAY_OFF_SUCCESS = "CREATE_DAY_OFF_SUCCESS";
export const CREATE_DAY_OFF_ERROR = "CREATE_DAY_OFF_ERROR";

export const FETCH_DAY_OFF_LIST_START = "FETCH_DAY_OFF_LIST_START";
export const FETCH_DAY_OFF_LIST_SUCCESS = "FETCH_DAY_OFF_LIST_SUCCESS";
export const FETCH_DAY_OFF_LIST_ERROR = "FETCH_DAY_OFF_LIST_ERROR";

export const DELETE_DAY_OFF_START = "DELETE_DAY_OFF_START";
export const DELETE_DAY_OFF_SUCCESS = "DELETE_DAY_OFF_SUCCESS";
export const DELETE_DAY_OFF_ERROR = "DELETE_DAY_OFF_ERROR";

export const RESET_DAY_OFF_LIST = "RESET_DAY_OFF_LIST";
export const RESET_DAY_OFF_LIST_ERROR = "RESET_DAY_OFF_LIST_ERROR";