export const FETCH_INSTRUCTOR_LIST_START = "FETCH_INSTRUCTOR_LIST_START";
export const FETCH_INSTRUCTOR_LIST_SUCCESS = "FETCH_INSTRUCTOR_LIST_SUCCESS";
export const FETCH_INSTRUCTOR_LIST_ERROR = "FETCH_INSTRUCTOR_LIST_ERROR";

export const FETCH_INSTRUCTOR_START = "FETCH_INSTRUCTOR_START";
export const FETCH_INSTRUCTOR_SUCCESS = "FETCH_INSTRUCTOR_SUCCESS";
export const FETCH_INSTRUCTOR_ERROR = "FETCH_INSTRUCTOR_ERROR";

export const CREATE_INSTRUCTOR_START = "CREATE_INSTRUCTOR_START";
export const CREATE_INSTRUCTOR_SUCCESS = "CREATE_INSTRUCTOR_SUCCESS";
export const CREATE_INSTRUCTOR_ERROR = "CREATE_INSTRUCTOR_ERROR";

export const DELETE_INSTRUCTOR_START = "DELETE_INSTRUCTOR_START";
export const DELETE_INSTRUCTOR_SUCCESS = "DELETE_INSTRUCTOR_SUCCESS";
export const DELETE_INSTRUCTOR_ERROR = "DELETE_INSTRUCTOR_ERROR";

export const UPDATE_INSTRUCTOR_ROLE_START = "UPDATE_INSTRUCTOR_ROLE_START";
export const UPDATE_INSTRUCTOR_ROLE_SUCCESS = "UPDATE_INSTRUCTOR_ROLE_SUCCESS";
export const UPDATE_INSTRUCTOR_ROLE_ERROR = "UPDATE_INSTRUCTOR_ROLE_ERROR";

export const CLEAR_INSTRUCTOR_REDUCER = "CLEAR_INSTRUCTOR_REDUCER";