const EMAILS_TYPES = {
    FETCH_EMAILS_TEMPLATES_LIST: 'FETCH_EMAILS_TEMPLATES_LIST',
    FETCH_EMAILS_TEMPLATES_LIST_SUCCESS: 'FETCH_EMAILS_TEMPLATES_LIST_SUCCESS',
    FETCH_EMAILS_TEMPLATES_LIST_ERROR: 'FETCH_EMAILS_TEMPLATES_LIST_ERROR',
    FETCH_EMAILS_TEMPLATES_LIST_CANCEL: 'FETCH_EMAILS_TEMPLATES_LIST_CANCEL',
    FETCH_EMAILS_TEMPLATES_LIST_RESET: 'FETCH_EMAILS_TEMPLATES_LIST_RESET',

    FETCH_EMAILS_TEMPLATES_BY_ID: 'FETCH_EMAILS_TEMPLATES_BY_ID',
    FETCH_EMAILS_TEMPLATES_BY_ID_SUCCESS: 'FETCH_EMAILS_TEMPLATES_BY_ID_SUCCESS',
    FETCH_EMAILS_TEMPLATES_BY_ID_ERROR: 'FETCH_EMAILS_TEMPLATES_BY_ID_ERROR',

    UPDATE_EMAILS_TEMPLATES_BY_ID: 'UPDATE_EMAILS_TEMPLATES_BY_ID',
    UPDATE_EMAILS_TEMPLATES_BY_ID_SUCCESS: 'UPDATE_EMAILS_TEMPLATES_BY_ID_SUCCESS',
    UPDATE_EMAILS_TEMPLATES_BY_ID_ERROR: 'UPDATE_EMAILS_TEMPLATES_BY_ID_ERROR',

};

export default EMAILS_TYPES;