export const GET_ALL_LESSONS_START = "GET_ALL_LESSONS_START";
export const GET_ALL_LESSONS_SUCCESS = "GET_ALL_LESSONS_SUCCESS";
export const GET_ALL_LESSONS_ERROR = "GET_ALL_LESSONS_ERROR";

export const GET_LESSON_START = "GET_LESSON_START";
export const GET_LESSON_SUCCESS = "GET_LESSON_SUCCESS";
export const GET_LESSON_ERROR = "GET_LESSON_ERROR";

export const CREATE_LESSON_START = "CREATE_LESSON_START";
export const CREATE_LESSON_SUCCESS = "CREATE_LESSON_SUCCESS";
export const CREATE_LESSON_ERROR = "CREATE_LESSON_ERROR";

export const UPDATE_LESSON_START = "UPDATE_LESSON_START";
export const UPDATE_LESSON_SUCCESS = "UPDATE_LESSON_SUCCESS";
export const UPDATE_LESSON_ERROR = "UPDATE_LESSON_ERROR";

export const UPDATE_LESSON_STATUS_START = "UPDATE_LESSON_STATUS_START";
export const UPDATE_LESSON_STATUS_SUCCESS = "UPDATE_LESSON_STATUS_SUCCESS";
export const UPDATE_LESSON_STATUS_ERROR = "UPDATE_LESSON_STATUS_ERROR";

export const DELETE_LESSON_START = "DELETE_LESSON_START";
export const DELETE_LESSON_SUCCESS = "DELETE_LESSON_SUCCESS";
export const DELETE_LESSON_ERROR = "DELETE_LESSON_ERROR";

export const RESET_LESSON = "RESET_LESSON";