export const CourseActionTypes = {
  SET_SECTION_MENU: "SET_SECTION_MENU",
  CLEAR_SECTION_MENU: "CLEAR_SECTION_MENU",

  SET_QUIZ_QUESTION: "SET_QUIZ_QUESTION",
  CLEAR_QUIZ_QUESTION: "CLEAR_QUIZ_QUESTION",

  LESSON_PREVIEW_DATA: "LESSON_PREVIEW_DATA",
  CLEAR_LESSON_PREVIEW_DATA: "CLEAR_LESSON_PREVIEW_DATA",

  GET_COURSES: "GET_COURSES",
  GET_COURSES_SUCCESS: "GET_COURSES_SUCCESS",
  GET_COURSES_ERROR: "GET_COURSES_ERROR",

  GET_COURSE_BY_ID: "GET_COURSE_BY_ID",
  GET_COURSE_BY_ID_SUCCESS: "GET_COURSE_BY_ID_SUCCESS",
  GET_COURSE_BY_ID_ERROR: "GET_COURSE_BY_ID_ERROR",

  CREATE_COURSE: "CREATE_COURSE",
  CREATE_COURSE_SUCCESS: "CREATE_COURSE_SUCCESS",
  CREATE_COURSE_ERROR: "CREATE_COURSE_ERROR",

  DELETE_COURSE: "DELETE_COURSE",
  DELETE_COURSE_SUCCESS: "DELETE_COURSE_SUCCESS",
  DELETE_COURSE_ERROR: "DELETE_COURSE_ERROR",

  UPDATE_COURSE: "UPDATE_COURSE",
  UPDATE_COURSE_SUCCESS: "UPDATE_COURSE_SUCCESS",
  UPDATE_COURSE_ERROR: "UPDATE_COURSE_ERROR",

  GET_UNITS_BY_COURSE_ID: "GET_UNITS_BY_COURSE_IDUNITS",
  GET_UNITS_BY_COURSE_ID_SUCCESS: "GET_UNITS_BY_COURSE_ID_SUCCESS",
  GET_UNITS_BY_COURSE_ID_ERROR: "GET_UNITS_BY_COURSE_ID_ERROR",

  GET_UNITS_BY_COURSE_UNIT_ID: "GET_UNITS_BY_COURSE_UNIT_ID",
  GET_UNITS_BY_COURSE_UNIT_ID_SUCCESS: "GET_UNITS_BY_COURSE_UNIT_ID_SUCCESS",
  GET_UNITS_BY_COURSE_UNIT_ID_ERROR: "GET_UNITS_BY_COURSE_UNIT_ID_ERROR",

  CREATE_UNIT: "CREATE_UNIT",
  CREATE_UNIT_SUCCESS: "CREATE_UNIT_SUCCESS",
  CREATE_UNIT_ERROR: "CREATE_UNIT_ERROR",

  UPDATE_UNIT: "UPDATE_UNIT",
  UPDATE_UNIT_SUCCESS: "UPDATE_UNIT_SUCCESS",
  UPDATE_UNIT_ERROR: "UPDATE_UNIT_ERROR",

  DELETE_UNIT: "DELETE_UNIT",
  DELETE_UNIT_SUCCESS: "DELETE_UNIT_SUCCESS",
  DELETE_UNIT_ERROR: "DELETE_UNIT_ERROR",

  GET_COURSE_LESSON: "GET_COURSE_LESSON",
  GET_COURSE_LESSON_SUCCESS: "GET_COURSE_LESSON_SUCCESS",
  GET_COURSE_LESSON_ERROR: "GET_COURSE_LESSON_ERROR",

  GET_COURSE_LESSON_BY_ID: "GET_COURSE_LESSON_BY_ID",
  GET_COURSE_LESSON_BY_ID_SUCCESS: "GET_COURSE_LESSON_BY_ID_SUCCESS",
  GET_COURSE_LESSON_BY_ID_ERROR: "GET_COURSE_LESSON_BY_ID_ERROR",

  CREATE_COURSE_LESSON_CONTENT: "CREATE_COURSE_LESSON_CONTENT",
  CREATE_COURSE_LESSON_CONTENT_SUCCESS: "CREATE_COURSE_LESSON_CONTENT_SUCCESS",
  CREATE_COURSE_LESSON_CONTENT_ERROR: "CREATE_COURSE_LESSON_CONTENT_ERROR",

  CREATE_COURSE_LESSON_VIDEO: "CREATE_COURSE_LESSON_VIDEO",
  CREATE_COURSE_LESSON_VIDEO_SUCCESS: "CREATE_COURSE_LESSON_VIDEO_SUCCESS",
  CREATE_COURSE_LESSON_VIDEO_ERROR: "CREATE_COURSE_LESSON_VIDEO_ERROR",

  CREATE_COURSE_LESSON_CHART: "CREATE_COURSE_LESSON_CHART",
  CREATE_COURSE_LESSON_CHART_SUCCESS: "CREATE_COURSE_LESSON_CHART_SUCCESS",
  CREATE_COURSE_LESSON_CHART_ERROR: "CREATE_COURSE_LESSON_CHART_ERROR",

  UPDATE_COURSE_LESSON: "UPDATE_COURSE_LESSON",
  UPDATE_COURSE_LESSON_SUCCESS: "UPDATE_COURSE_LESSON_SUCCESS",
  UPDATE_COURSE_LESSON_ERROR: "UPDATE_COURSE_LESSON_ERROR",

  DELETE_COURSE_LESSON: "DELETE_COURSE_LESSON",
  DELETE_COURSE_LESSON_SUCCESS: "DELETE_COURSE_LESSON_SUCCESS",
  DELETE_COURSE_LESSON_ERROR: "DELETE_COURSE_LESSON_ERROR",

  GET_COURSE_SUBUNIT: "GET_COURSE_SUBUNIT",
  GET_COURSE_SUBUNIT_SUCCESS: "GET_COURSE_SUBUNIT_SUCCESS",
  GET_COURSE_SUBUNIT_ERROR: "GET_COURSE_SUBUNIT_ERROR",

  CREATE_COURSE_SUBUNIT: "CREATE_COURSE_SUBUNIT",
  CREATE_COURSE_SUBUNIT_SUCCESS: "CREATE_COURSE_SUBUNIT_SUCCESS",
  CREATE_COURSE_SUBUNIT_ERROR: "CREATE_COURSE_SUBUNIT_ERROR",

  UPDATE_COURSE_SUBUNIT: "UPDATE_COURSE_SUBUNIT",
  UPDATE_COURSE_SUBUNIT_SUCCESS: "UPDATE_COURSE_SUBUNIT_SUCCESS",
  UPDATE_COURSE_SUBUNIT_ERROR: "UPDATE_COURSE_SUBUNIT_ERROR",

  DELETE_COURSE_SUBUNIT: "DELETE_COURSE_SUBUNIT",
  DELETE_COURSE_SUBUNIT_SUCCESS: "DELETE_COURSE_SUBUNIT_SUCCESS",
  DELETE_COURSE_SUBUNIT_ERROR: "DELETE_COURSE_SUBUNIT_ERROR",

  GET_COURSE_QUESTION: "GET_COURSE_QUESTION",
  GET_COURSE_QUESTION_SUCCESS: "GET_COURSE_QUESTION_SUCCESS",
  GET_COURSE_QUESTION_ERROR: "GET_COURSE_QUESTION_ERROR",

  CREATE_COURSE_QUESTION: "CREATE_COURSE_QUESTION",
  CREATE_COURSE_QUESTION_SUCCESS: "CREATE_COURSE_QUESTION_SUCCESS",
  CREATE_COURSE_QUESTION_ERROR: "CREATE_COURSE_QUESTION_ERROR",

  UPDATE_COURSE_QUESTION: "UPDATE_COURSE_QUESTION",
  UPDATE_COURSE_QUESTION_SUCCESS: "UPDATE_COURSE_QUESTION_SUCCESS",
  UPDATE_COURSE_QUESTION_ERROR: "UPDATE_COURSE_QUESTION_ERROR",

  DELETE_COURSE_QUESTION: "DELETE_COURSE_QUESTION",
  DELETE_COURSE_QUESTION_SUCCESS: "DELETE_COURSE_QUESTION_SUCCESS",
  DELETE_COURSE_QUESTION_ERROR: "DELETE_COURSE_QUESTION_ERROR",

  GET_COURSE_QUIZ: "GET_COURSE_QUIZ",
  GET_COURSE_QUIZ_SUCCESS: "GET_COURSE_QUIZ_SUCCESS",
  GET_COURSE_QUIZ_ERROR: "GET_COURSE_QUIZ_ERROR",

  CREATE_COURSE_QUIZ: "CREATE_COURSE_QUIZ",
  CREATE_COURSE_QUIZ_SUCCESS: "CREATE_COURSE_QUIZ_SUCCESS",
  CREATE_COURSE_QUIZ_ERROR: "CREATE_COURSE_QUIZ_ERROR",

  UPDATE_COURSE_QUIZ: "UPDATE_COURSE_QUIZ",
  UPDATE_COURSE_QUIZ_SUCCESS: "UPDATE_COURSE_QUIZ_SUCCESS",
  UPDATE_COURSE_QUIZ_ERROR: "UPDATE_COURSE_QUIZ_ERROR",

  DELETE_COURSE_QUIZ: "DELETE_COURSE_QUIZ",
  DELETE_COURSE_QUIZ_SUCCESS: "DELETE_COURSE_QUIZ_SUCCESS",
  DELETE_COURSE_QUIZ_ERROR: "DELETE_COURSE_QUIZ_ERROR",
};
