export const CertificateTypes = {
    GET_ASSIGNED_USER_CERTIFICATE_GOLD: 'GET_ASSIGNED_USER_CERTIFICATE_GOLD',
    GET_ASSIGNED_USER_CERTIFICATE_GOLD_SUCCESS: 'GET_ASSIGNED_USER_CERTIFICATE_GOLD_SUCCESS',
    GET_ASSIGNED_USER_CERTIFICATE_GOLD_FAILURE: 'GET_ASSIGNED_USER_CERTIFICATE_GOLD_FAILURE',

    GET_ASSIGNED_USER_CERTIFICATE_PINK: 'GET_ASSIGNED_USER_CERTIFICATE_PINK',
    GET_ASSIGNED_USER_CERTIFICATE_PINK_SUCCESS: 'GET_ASSIGNED_USER_CERTIFICATE_PINK_SUCCESS',
    GET_ASSIGNED_USER_CERTIFICATE_PINK_FAILURE: 'GET_ASSIGNED_USER_CERTIFICATE_PINK_FAILURE',

    UPDATE_USER_CERTIFICATE_STATUS: 'UPDATE_USER_CERTIFICATE_STATUS',
    UPDATE_USER_CERTIFICATE_STATUS_SUCCESS: 'UPDATE_USER_CERTIFICATE_STATUS_SUCCESS',
    UPDATE_USER_CERTIFICATE_STATUS_FAILURE: 'UPDATE_USER_CERTIFICATE_STATUS_FAILURE',

    GET_USER_CERTIFICATE_BY_USER_ID: "GET_USER_CERTIFICATE_BY_USER_ID",
    GET_USER_CERTIFICATE_BY_USER_ID_SUCCESS: "GET_USER_CERTIFICATE_BY_USER_ID_SUCCESS",
    GET_USER_CERTIFICATE_BY_USER_ID_ERROR: "GET_USER_CERTIFICATE_BY_USER_ID_ERROR",
}