export const FETCH_USER_LIST_START = "FETCH_USER_LIST_START";
export const FETCH_USER_LIST_SUCCESS = "FETCH_USER_LIST_SUCCESS";
export const FETCH_USER_LIST_ERROR = "FETCH_USER_LIST_ERROR";

export const FETCH_USER_START = "FETCH_USER_START";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_ERROR = "FETCH_USER_ERROR";

export const FETCH_USER_BY_ID_START = "FETCH_USER_BY_ID_START";
export const FETCH_USER_BY_ID_SUCCESS = "FETCH_USER_BY_ID_SUCCESS";
export const FETCH_USER_BY_ID_ERROR = "FETCH_USER_BY_ID_ERROR";

export const CREATE_USER_START = "CREATE_USER_START";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_ERROR = "CREATE_USER_ERROR";

export const DELETE_USER_START = "DELETE_USER_START";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_ERROR = "DELETE_USER_ERROR";

export const UPDATE_USER_ROLE_START = "UPDATE_USER_ROLE_START";
export const UPDATE_USER_ROLE_SUCCESS = "UPDATE_USER_ROLE_SUCCESS";
export const UPDATE_USER_ROLE_ERROR = "UPDATE_USER_ROLE_ERROR";

export const CLEAR_USER_REDUCER = "CLEAR_USER_REDUCER";

export const FETCH_USER_DETAILS_START = "FETCH_USER_DETAILS_START";
export const FETCH_USER_DETAILS_SUCCESS = "FETCH_USER_DETAILS_SUCCESS";
export const FETCH_USER_DETAILS_ERROR = "FETCH_USER_DETAILS_ERROR";

export const UPDATE_USER_DETAILS_START = "UPDATE_USER_DETAILS_START";
export const UPDATE_USER_DETAILS_SUCCESS = "UPDATE_USER_DETAILS_SUCCESS";
export const UPDATE_USER_DETAILS_ERROR = "UPDATE_USER_DETAILS_ERROR";

export const UPLOAD_FILES_PDF_START = "UPLOAD_FILES_PDF_START";
export const UPLOAD_FILES_PDF_SUCCESS = "UPLOAD_FILES_PDF_SUCCESS";
export const UPLOAD_FILES_PDF_ERROR = "UPLOAD_FILES_PDF_ERROR";

export const ADD_INSTRUCTOR_NOTE_START = "ADD_INSTRUCTOR_NOTE_START";
export const ADD_INSTRUCTOR_NOTE_SUCCESS = "ADD_INSTRUCTOR_NOTE_SUCCESS";
export const ADD_INSTRUCTOR_NOTE_ERROR = "ADD_INSTRUCTOR_NOTE_ERROR";

export const UPDATE_INSTRUCTOR_NOTE_START = "UPDATE_INSTRUCTOR_NOTE_START";
export const UPDATE_INSTRUCTOR_NOTE_SUCCESS = "UPDATE_INSTRUCTOR_NOTE_SUCCESS";
export const UPDATE_INSTRUCTOR_NOTE_ERROR = "UPDATE_INSTRUCTOR_NOTE_ERROR";

export const FETCH_TRAINING_LOGS_BY_USER_ID_AND_LESSON_ID_START =
  "FETCH_TRAINING_LOGS_BY_USER_ID_AND_LESSON_ID_START";
export const FETCH_TRAINING_LOGS_BY_USER_ID_AND_LESSON_ID_SUCCESS =
  "FETCH_TRAINING_LOGS_BY_USER_ID_AND_LESSON_ID_SUCCESS";
export const FETCH_TRAINING_LOGS_BY_USER_ID_AND_LESSON_ID_ERROR =
  "FETCH_TRAINING_LOGS_BY_USER_ID_AND_LESSON_ID_ERROR";

export const CREATE_TRAINING_LOG_START = "CREATE_TRAINING_LOG_START";
export const CREATE_TRAINING_LOG_SUCCESS = "CREATE_TRAINING_LOG_SUCCESS";
export const CREATE_TRAINING_LOG_ERROR = "CREATE_TRAINING_LOG_ERROR";

export const UPDATE_TRAINING_LOG_START = "UPDATE_TRAINING_LOG_START";
export const UPDATE_TRAINING_LOG_SUCCESS = "UPDATE_TRAINING_LOG_SUCCESS";
export const UPDATE_TRAINING_LOG_ERROR = "UPDATE_TRAINING_LOG_ERROR";

export const GET_INSTRUCTOR_NOTES_BY_USER_ID =
  "GET_INSTRUCTOR_NOTES_BY_USER_ID";
export const GET_INSTRUCTOR_NOTES_BY_USER_ID_SUCCESS =
  "GET_INSTRUCTOR_NOTES_BY_USER_ID_SUCCESS";
export const GET_INSTRUCTOR_NOTES_BY_USER_ID_ERROR =
  "GET_INSTRUCTOR_NOTES_BY_USER_ID_ERROR";

export const UPDATE_USER_DETAILS_FROM_LIST_START =
  "UPDATE_USER_DETAILS_FROM_LIST_START";
export const UPDATE_USER_DETAILS_FROM_LIST_SUCCESS =
  "UPDATE_USER_DETAILS_FROM_LIST_SUCCESS";
export const UPDATE_USER_DETAILS_FROM_LIST_ERROR =
  "UPDATE_USER_DETAILS_FROM_LIST_ERROR";

export const UPDATE_USER_STATUS_START = "UPDATE_USER_STATUS_START";
export const UPDATE_USER_STATUS_SUCCESS = "UPDATE_USER_STATUS_SUCCESS";
export const UPDATE_USER_STATUS_ERROR = "UPDATE_USER_STATUS_ERROR";

export const UPDATE_INSTRUCTOR_START = "UPDATE_INSTRUCTOR_START";
export const UPDATE_INSTRUCTOR_SUCCESS = "UPDATE_INSTRUCTOR_SUCCESS";
export const UPDATE_INSTRUCTOR_ERROR = "UPDATE_INSTRUCTOR_ERROR";

export const FETCH_INSTRUCTOR_START = "FETCH_INSTRUCTOR_START";
export const FETCH_INSTRUCTOR_SUCCESS = "FETCH_INSTRUCTOR_SUCCESS";
export const FETCH_INSTRUCTOR_ERROR = "FETCH_INSTRUCTOR_ERROR";
export const CLEAR_INSTRUCTOR = "CLEAR_INSTRUCTOR";

export const UPDATE_USER_LOCK_STATUS_START = "UPDATE_USER_LOCK_STATUS_START";
export const UPDATE_USER_LOCK_STATUS_SUCCESS = "UPDATE_USER_LOCK_STATUS_SUCCESS";
export const UPDATE_USER_LOCK_STATUS_ERROR = "UPDATE_USER_LOCK_STATUS_ERROR";
