export const BLOGS_TYPES = {
    "CREATE_BLOG_START": "CREATE_BLOG_START",
    "CREATE_BLOG_SUCCESS": "CREATE_BLOG_SUCCESS",
    "CREATE_BLOG_FAILURE": "CREATE_BLOG_FAILURE",

    "FETCH_BLOGS_START": "FETCH_BLOGS_START",
    "FETCH_BLOGS_SUCCESS": "FETCH_BLOGS_SUCCESS",
    "FETCH_BLOGS_FAILURE": "FETCH_BLOGS_FAILURE",

    "UPDATE_BLOGS_START" : "UPDATE_BLOGS_START",
    "UPDATE_BLOGS_SUCCESS" : "UPDATE_BLOGS_SUCCESS",
    "UPDATE_BLOGS_FAILURE" : "UPDATE_BLOGS_FAILURE",

    "DELETE_BLOGS_START" : "DELETE_BLOGS_START",
    "DELETE_BLOGS_SUCCESS" : "DELETE_BLOGS_SUCCESS",
    "DELETE_BLOGS_FAILURE" : "DELETE_BLOGS_FAILURE",
}