export const GET_ALL_PACKAGE_START = "GET_ALL_PACKAGE_START";
export const GET_ALL_PACKAGE_SUCCESS = "GET_ALL_PACKAGE_SUCCESS";
export const GET_ALL_PACKAGE_ERROR = "GET_ALL_PACKAGE_ERROR";

export const GET_PACKAGE_START = "GET_PACKAGE_START";
export const GET_PACKAGE_SUCCESS = "GET_PACKAGE_SUCCESS";
export const GET_PACKAGE_ERROR = "GET_PACKAGE_ERROR";

export const CREATE_PACKAGE_START = "CREATE_PACKAGE_START";
export const CREATE_PACKAGE_SUCCESS = "CREATE_PACKAGE_SUCCESS";
export const CREATE_PACKAGE_ERROR = "CREATE_PACKAGE_ERROR";

export const UPDATE_PACKAGE_START = "UPDATE_PACKAGE_START";
export const UPDATE_PACKAGE_SUCCESS = "UPDATE_PACKAGE_SUCCESS";
export const UPDATE_PACKAGE_ERROR = "UPDATE_PACKAGE_ERROR";

export const UPDATE_PACKAGE_STATUS_START = "UPDATE_PACKAGE_STATUS_START";
export const UPDATE_PACKAGE_STATUS_SUCCESS = "UPDATE_PACKAGE_STATUS_SUCCESS";
export const UPDATE_PACKAGE_STATUS_ERROR = "UPDATE_PACKAGE_STATUS_ERROR";

export const DELETE_PACKAGE_START = "DELETE_PACKAGE_START";
export const DELETE_PACKAGE_SUCCESS = "DELETE_PACKAGE_SUCCESS";
export const DELETE_PACKAGE_ERROR = "DELETE_PACKAGE_ERROR";

export const RESET_PACKAGE = "RESET_PACKAGE";