const CONFIGURATION_TYPES = {
    CREATE_PAYMENT_CONFIGURATION: "CREATE_PAYMENT_CONFIGURATION",
    CREATE_PAYMENT_CONFIGURATION_SUCCESS: "CREATE_PAYMENT_CONFIGURATION_PAYMENT_SUCCESS",
    CREATE_PAYMENT_CONFIGURATION_ERROR: "CREATE_PAYMENT_CONFIGURATION_PAYMENT_ERROR",

    UPDATE_PAYMENT_CONFIGURATION: "UPDATE_PAYMENT_CONFIGURATION",
    UPDATE_PAYMENT_CONFIGURATION_SUCCESS: "UPDATE_PAYMENT_CONFIGURATION_SUCCESS",
    UPDATE_PAYMENT_CONFIGURATION_ERROR: "UPDATE_PAYMENT_CONFIGURATION_ERROR",

    GET_DRIVING_SCHOOL_BASIC_CONFIGURATION: "GET_DRIVING_SCHOOL_BASIC_CONFIGURATION",
    GET_DRIVING_SCHOOL_BASIC_CONFIGURATION_SUCCESS: "GET_DRIVING_SCHOOL_BASIC_CONFIGURATION_SUCCESS",
    GET_DRIVING_SCHOOL_BASIC_CONFIGURATION_ERROR: "GET_DRIVING_SCHOOL_BASIC_CONFIGURATION_ERROR",

    UPDATE_DRIVING_SCHOOL_BASIC_CONFIGURATION: "UPDATE_DRIVING_SCHOOL_BASIC_CONFIGURATION",
    UPDATE_DRIVING_SCHOOL_BASIC_CONFIGURATION_SUCCESS: "UPDATE_DRIVING_SCHOOL_BASIC_CONFIGURATION_SUCCESS",
    UPDATE_DRIVING_SCHOOL_BASIC_CONFIGURATION_ERROR: "UPDATE_DRIVING_SCHOOL_BASIC_CONFIGURATION_ERROR",

    UPDATE_DRIVING_SCHOOL_LOGO: "UPDATE_DRIVING_SCHOOL_LOGO",
    UPDATE_DRIVING_SCHOOL_LOGO_SUCCESS: "UPDATE_DRIVING_SCHOOL_LOGO_SUCCESS",
    UPDATE_DRIVING_SCHOOL_LOGO_ERROR: "UPDATE_DRIVING_SCHOOL_LOGO_ERROR",
    
    CREATE_DRIVING_SCHOOL: "CREATE_DRIVING_SCHOOL",
    CREATE_DRIVING_SCHOOL_SUCCESS: "CREATE_DRIVING_SCHOOL_SUCCESS",
    CREATE_DRIVING_SCHOOL_ERROR: "CREATE_DRIVING_SCHOOL_ERROR",
}

export default CONFIGURATION_TYPES;