export const FETCH_TRANSACTIONS_START = "FETCH_TRANSACTIONS_START";
export const FETCH_TRANSACTIONS_SUCCESS = "FETCH_TRANSACTIONS_SUCCESS";
export const FETCH_TRANSACTIONS_FAILURE = "FETCH_TRANSACTIONS_FAILURE";

export const CREATE_TRANSACTION_START = "CREATE_TRANSACTION_START";
export const CREATE_TRANSACTION_SUCCESS = "CREATE_TRANSACTION_SUCCESS";
export const CREATE_TRANSACTION_FAILURE = "CREATE_TRANSACTION_FAILURE";

export const DELETE_TRANSACTION_START = "DELETE_TRANSACTION_START";
export const DELETE_TRANSACTION_SUCCESS = "DELETE_TRANSACTION_SUCCESS";
export const DELETE_TRANSACTION_FAILURE = "DELETE_TRANSACTION_FAILURE";

export const FETCH_TRANSACTIONS_BY_USER_ID_START =
  "FETCH_TRANSACTIONS_BY_USER_ID_START";
export const FETCH_TRANSACTIONS_BY_USER_ID_SUCCESS =
  "FETCH_TRANSACTIONS_BY_USER_ID_SUCCESS";
export const FETCH_TRANSACTIONS_BY_USER_ID_FAILURE =
  "FETCH_TRANSACTIONS_BY_USER_ID_FAILURE";

export const FETCH_PENDING_TRANSACTIONS_BY_USER_ID_START =
  "FETCH_PENDING_TRANSACTIONS_BY_USER_ID_START";
export const FETCH_PENDING_TRANSACTIONS_BY_USER_ID_SUCCESS =
  "FETCH_PENDING_TRANSACTIONS_BY_USER_ID_SUCCESS";
export const FETCH_PENDING_TRANSACTIONS_BY_USER_ID_FAILURE =
  "FETCH_PENDING_TRANSACTIONS_BY_USER_ID_FAILURE";

export const FETCH_TRANSACTIONS_BY_ID_START = "FETCH_TRANSACTIONS_BY_ID_START";
export const FETCH_TRANSACTIONS_BY_ID_SUCCESS =
  "FETCH_TRANSACTIONS_BY_ID_SUCCESS";
export const FETCH_TRANSACTIONS_BY_ID_FAILURE =
  "FETCH_TRANSACTIONS_BY_ID_FAILURE";

export const UPDATE_TRANSACTION_START = "UPDATE_TRANSACTION_START";
export const UPDATE_TRANSACTION_SUCCESS = "UPDATE_TRANSACTION_SUCCESS";
export const UPDATE_TRANSACTION_FAILURE = "UPDATE_TRANSACTION_FAILURE";

export const FETCH_EMAIL_LOGS_START = "FETCH_EMAIL_LOGS_START";
export const FETCH_EMAIL_LOGS_SUCCESS = "FETCH_EMAIL_LOGS_SUCCESS";
export const FETCH_EMAIL_LOGS_FAILURE = "FETCH_EMAIL_LOGS_FAILURE";
