export const FETCH_APPOINTMENTS = 'FETCH_APPOINTMENTS';
export const FETCH_APPOINTMENTS_SUCCESS = 'FETCH_APPOINTMENTS_SUCCESS';
export const FETCH_APPOINTMENTS_FAILURE = 'FETCH_APPOINTMENTS_FAILURE';

export const FETCH_APPOINTMENTS_BY_USER_ID = 'FETCH_APPOINTMENTS_BY_USER_ID';
export const FETCH_APPOINTMENTS_BY_USER_ID_SUCCESS = 'FETCH_APPOINTMENTS_BY_USER_ID_SUCCESS';
export const FETCH_APPOINTMENTS_BY_USER_ID_FAILURE = 'FETCH_APPOINTMENTS_BY_USER_ID_FAILURE';

export const FETCH_APPOINTMENTS_BY_DATE = 'FETCH_APPOINTMENTS_BY_DATE';
export const FETCH_APPOINTMENTS_BY_DATE_SUCCESS = 'FETCH_APPOINTMENTS_BY_DATE_SUCCESS';
export const FETCH_APPOINTMENTS_BY_DATE_FAILURE = 'FETCH_APPOINTMENTS_BY_DATE_FAILURE';

export const FETCH_APPOINTMENT_OF_PAY_PERIOD = 'FETCH_APPOINTMENT_OF_PAY_PERIOD';
export const FETCH_APPOINTMENT_OF_PAY_PERIOD_SUCCESS = 'FETCH_APPOINTMENT_OF_PAY_PERIOD_SUCCESS';
export const FETCH_APPOINTMENT_OF_PAY_PERIOD_FAILURE = 'FETCH_APPOINTMENT_OF_PAY_PERIOD_FAILURE';

export const CREATE_APPOINTMENT = 'CREATE_APPOINTMENT';
export const CREATE_APPOINTMENT_SUCCESS = 'CREATE_APPOINTMENT_SUCCESS';
export const CREATE_APPOINTMENT_FAILURE = 'CREATE_APPOINTMENT_FAILURE';

export const UPDATE_APPOINTMENT = 'UPDATE_APPOINTMENT';
export const UPDATE_APPOINTMENT_SUCCESS = 'UPDATE_APPOINTMENT_SUCCESS';
export const UPDATE_APPOINTMENT_FAILURE = 'UPDATE_APPOINTMENT_FAILURE';

export const DELETE_APPOINTMENT = 'DELETE_APPOINTMENT';
export const DELETE_APPOINTMENT_SUCCESS = 'DELETE_APPOINTMENT_SUCCESS';
export const DELETE_APPOINTMENT_FAILURE = 'DELETE_APPOINTMENT_FAILURE';

export const FETCH_APPOINTMENT = 'FETCH_APPOINTMENT';
export const FETCH_APPOINTMENT_SUCCESS = 'FETCH_APPOINTMENT_SUCCESS';
export const FETCH_APPOINTMENT_FAILURE = 'FETCH_APPOINTMENT_FAILURE';

export const UPDATE_APPOINTMENT_STATUS = 'UPDATE_APPOINTMENT_STATUS';
export const UPDATE_APPOINTMENT_STATUS_SUCCESS = "UDPATE_APPOINTMNET_STATUS_SUCCESS";
export const UPDATE_APPOINTMENT_STATUS_FAILURE = "UDPATE_APPOINTMNET_STATUS_FAILURE";

export const RESET_APPOINTMENT = 'RESET_APPOINTMENT';