export const FETCH_UNITS_LIST_START = "FETCH_UNITS_LIST_START";
export const FETCH_UNITS_LIST_SUCCESS = "FETCH_UNITS_LIST_SUCCESS";
export const FETCH_UNITS_LIST_ERROR = "FETCH_UNITS_LIST_ERROR";

export const FETCH_UNITS_LESSONS_BY_ID_START =
  "FETCH_UNITS_LESSONS_BY_ID_START";
export const FETCH_UNITS_LESSONS_BY_ID_SUCCESS =
  "FETCH_UNITS_LESSONS_BY_ID_SUCCESS";
export const FETCH_UNITS_LESSONS_BY_ID_ERROR =
  "FETCH_UNITS_LESSONS_BY_ID_ERROR";

export const FETCH_LESSON_DETAILS_START = "FETCH_LESSON_DETAILS_START";
export const FETCH_LESSON_DETAILS_SUCCESS = "FETCH_LESSON_DETAILS_SUCCESS";
export const FETCH_LESSON_DETAILS_ERROR = "FETCH_LESSON_DETAILS_ERROR";

export const FETCH_UNIT_QUIZ_BY_ID_START = "FETCH_UNIT_QUIZ_BY_ID_START";
export const FETCH_UNIT_QUIZ_BY_ID_SUCCESS = "FETCH_UNIT_QUIZ_BY_ID_SUCCESS";
export const FETCH_UNIT_QUIZ_BY_ID_ERROR = "FETCH_UNIT_QUIZ_BY_ID_ERROR";

export const SUBMIT_UNIT_QUIZ_START = "SUBMIT_UNIT_QUIZ_START";
export const SUBMIT_UNIT_QUIZ_SUCCESS = "SUBMIT_UNIT_QUIZ_SUCCESS";
export const SUBMIT_UNIT_QUIZ_ERROR = "SUBMIT_UNIT_QUIZ_ERROR";

export const FETCH_VIDEO_LIST_START = "FETCH_VIDEO_LIST_START";
export const FETCH_VIDEO_LIST_SUCCESS = "FETCH_VIDEO_LIST_SUCCESS";
export const FETCH_VIDEO_LIST_ERROR = "FETCH_VIDEO_LIST_ERROR";

export const FETCH_CHART_LIST_START = "FETCH_CHART_LIST_START";
export const FETCH_CHART_LIST_SUCCESS = "FETCH_CHART_LIST_SUCCESS";
export const FETCH_CHART_LIST_ERROR = "FETCH_CHART_LIST_ERROR";

export const FETCH_CHART_BY_ID_START = "FETCH_CHART_BY_ID_START";
export const FETCH_CHART_BY_ID_SUCCESS = "FETCH_CHART_BY_ID_SUCCESS";
export const FETCH_CHART_BY_ID_ERROR = "FETCH_CHART_BY_ID_ERROR";

export const FETCH_FINAL_EXAM_START = "FETCH_FINAL_EXAM_START";
export const FETCH_FINAL_EXAM_SUCCESS = "FETCH_FINAL_EXAM_SUCCESS";
export const FETCH_FINAL_EXAM_ERROR = "FETCH_FINAL_EXAM_ERROR";

export const SUBMIT_FINAL_EXAM_START = "SUBMIT_FINAL_EXAM_START";
export const SUBMIT_FINAL_EXAM_SUCCESS = "SUBMIT_FINAL_EXAM_SUCCESS";
export const SUBMIT_FINAL_EXAM_ERROR = "SUBMIT_FINAL_EXAM_ERROR";

export const FETCH_STUDENT_TEST_STATUS_START =
  "FETCH_STUDENT_TEST_STATUS_START";
export const FETCH_STUDENT_TEST_STATUS_SUCCESS =
  "FETCH_STUDENT_TEST_STATUS_SUCCESS";
export const FETCH_STUDENT_TEST_STATUS_ERROR =
  "FETCH_STUDENT_TEST_STATUS_ERROR";

export const FETCH_STUDENT_PROGRESS_START =
  "FETCH_STUDENT_PROGRESS_START";
export const FETCH_STUDENT_PROGRESS_SUCCESS =
  "FETCH_STUDENT_PROGRESS_SUCCESS";
export const FETCH_STUDENT_PROGRESS_ERROR =
  "FETCH_STUDENT_PROGRESS_ERROR";
